
import java.awt.Desktop;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.io.FileUtils;
import org.apache.commons.io.FilenameUtils;
import twitter4j.MediaEntity;
import twitter4j.Paging;
import twitter4j.Status;
import twitter4j.Twitter;
import twitter4j.TwitterException;
import twitter4j.TwitterFactory;
import twitter4j.conf.ConfigurationBuilder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Sabri
 */
public class AnaJframe extends javax.swing.JFrame {

    Thread t;
    String klasor;
    Thread ts;

    /**
     * Creates new form AnaJframe
     */
    public AnaJframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        stopfield = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        logtext = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        linktablosu = new javax.swing.JTable();
        goster = new javax.swing.JButton();
        DownloadStartBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        startfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        goster1 = new javax.swing.JButton();
        DownloadStartBtn1 = new javax.swing.JButton();
        startfield1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        logtext1 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        linktablosu1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tumblr Downloader ByTRiSLaSiS");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        stopfield.setText("500");

        logtext.setColumns(20);
        logtext.setRows(5);
        jScrollPane2.setViewportView(logtext);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField1.setText("https://exampleblog.tumblr.com/");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Resimleri Getir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        linktablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Link", "Stats"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(linktablosu);
        if (linktablosu.getColumnModel().getColumnCount() > 0) {
            linktablosu.getColumnModel().getColumn(1).setMaxWidth(80);
        }

        goster.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        goster.setText("Göster");
        goster.setEnabled(false);
        goster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gosterActionPerformed(evt);
            }
        });

        DownloadStartBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DownloadStartBtn.setText("İNDİRMEYE BAŞLA");
        DownloadStartBtn.setEnabled(false);
        DownloadStartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownloadStartBtnActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Durdur");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        startfield.setText("0");

        jLabel1.setText("Start Page");

        jLabel2.setText(" End Page");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(DownloadStartBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startfield, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stopfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(goster))
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {startfield, stopfield});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(startfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(stopfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goster))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DownloadStartBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        jTabbedPane1.addTab("Tumblr", jPanel1);

        goster1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        goster1.setText("Göster");
        goster1.setEnabled(false);
        goster1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goster1ActionPerformed(evt);
            }
        });

        DownloadStartBtn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DownloadStartBtn1.setText("İNDİRMEYE BAŞLA");
        DownloadStartBtn1.setEnabled(false);
        DownloadStartBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownloadStartBtn1ActionPerformed(evt);
            }
        });

        startfield1.setText("1");

        jLabel3.setText("Total Page");

        logtext1.setColumns(20);
        logtext1.setRows(5);
        jScrollPane3.setViewportView(logtext1);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField2.setText("twitter-username");

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Resimleri Getir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        linktablosu1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Link", "Stats"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(linktablosu1);
        if (linktablosu1.getColumnModel().getColumnCount() > 0) {
            linktablosu1.getColumnModel().getColumn(1).setMaxWidth(80);
        }

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("Durdur");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DownloadStartBtn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(startfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(goster1))
                    .addComponent(jScrollPane3))
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(startfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(goster1)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DownloadStartBtn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Twitter", jPanel2);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Twitter Uygulama Ayarları"));

        jTextField3.setText("Consumer Key");

        jTextField4.setText("Consumer Secret");

        jTextField5.setText("Access Token");

        jTextField6.setText("Access Secret");

        jButton3.setText("Kaydet");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField3, jTextField4, jTextField5, jTextField6});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jLabel4.setText("Merhaba Arkadaşlar Twitterdaki Resimleri İndirmek İçin Twitterda Uygulama Oluşturmanız Gerekmekte Aksi Taktirde Sadece Tumblr Kullanabilirsiniz");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(125, 125, 125))
        );

        jTabbedPane1.addTab("Ayarlar", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.t = new Thread(() -> {
            try {
                DefaultTableModel dtm = (DefaultTableModel) linktablosu.getModel();
                dtm.setRowCount(0);

                GetLinks gl = new GetLinks(jTextField1.getText());
            } catch (IOException | InterruptedException ex) {
                Logger.getLogger(AnaJframe.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        t.start();

        jButton1.setEnabled(false);
        jButton2.setEnabled(true);
        DownloadStartBtn.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.t.stop();
        AnaJframe.jButton1.setEnabled(true);
        AnaJframe.DownloadStartBtn.setEnabled(true);
        jButton2.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void DownloadStartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownloadStartBtnActionPerformed
        File f = new File("");
        this.klasor = f.getAbsolutePath() + "\\Downloads\\" + jTextField1.getText().replaceAll("[^a-zA-Z0-9]", "").replaceAll("(https|http)", "").replaceAll("tumblrcom", "");
        File theDir = new File(this.klasor);
        if (!theDir.exists()) {
            boolean result = false;
            try {
                theDir.mkdir();
                result = true;
            } catch (SecurityException se) {
            }
        }

        Thread c = new Thread(new Runnable() {
            @Override
            public void run() {
                int Toplam = linktablosu.getRowCount();

                int gerisay = Toplam;
                for (int i = 0; i < Toplam; i++) {
                    try {

                        URL aURL = new URL((String) linktablosu.getValueAt(i, 0));
                        String name = FilenameUtils.getName(aURL.getPath());
                        File kaydet = new File(klasor + "\\" + name);
                        try {
                            DownloadStartBtn.setText("İNDİRMEYE BAŞLA (" + (--gerisay) + " Resim)");
                            FileUtils.copyURLToFile(aURL, kaydet);
                            linktablosu.setValueAt("Bitti", i, 1);
                        } catch (IOException ex) {
                            Logger.getLogger(AnaJframe.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } catch (MalformedURLException ex) {
                        Logger.getLogger(AnaJframe.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
        });
        c.start();

        goster.setEnabled(true);

    }//GEN-LAST:event_DownloadStartBtnActionPerformed

    private void gosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gosterActionPerformed

        File f = new File("");
        this.klasor = f.getAbsolutePath() + "\\Downloads\\" + jTextField1.getText().replaceAll("[^a-zA-Z0-9]", "").replaceAll("(https|http)", "").replaceAll("tumblrcom", "");

        Desktop desktop = Desktop.getDesktop();
        File dirToOpen = null;
        try {
            dirToOpen = new File(this.klasor);
            desktop.open(dirToOpen);
        } catch (IllegalArgumentException iae) {
            JOptionPane.showMessageDialog(null, "Klasör Bulunamadı", "Hata", 0);
        } catch (IOException ex) {
            Logger.getLogger(AnaJframe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gosterActionPerformed

    private void goster1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goster1ActionPerformed

        File f = new File("");
        this.klasor = f.getAbsolutePath() + "\\Downloads\\" + jTextField2.getText().replaceAll("[^a-zA-Z0-9]", "").replaceAll("(https|http)", "").replaceAll("tumblrcom", "");

        Desktop desktop = Desktop.getDesktop();
        File dirToOpen = null;
        try {
            dirToOpen = new File(this.klasor);
            desktop.open(dirToOpen);
        } catch (IllegalArgumentException iae) {
            JOptionPane.showMessageDialog(null, "Klasör Bulunamadı", "Hata", 0);
        } catch (IOException ex) {
            Logger.getLogger(AnaJframe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_goster1ActionPerformed

    private void DownloadStartBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownloadStartBtn1ActionPerformed
        File f = new File("");
        this.klasor = f.getAbsolutePath() + "\\Downloads\\" + jTextField2.getText().replaceAll("[^a-zA-Z0-9]", "").replaceAll("(https|http)", "").replaceAll("tumblrcom", "");
        File theDir = new File(this.klasor);
        if (!theDir.exists()) {
            boolean result = false;
            try {
                theDir.mkdir();
                result = true;
            } catch (SecurityException se) {
            }
        }

        Thread c = new Thread(new Runnable() {
            @Override
            public void run() {
                int Toplam = linktablosu1.getRowCount();

                int gerisay = Toplam;
                for (int i = 0; i < Toplam; i++) {
                    try {

                        URL aURL = new URL((String) linktablosu1.getValueAt(i, 0));
                        String name = FilenameUtils.getName(aURL.getPath());
                        File kaydet = new File(klasor + "\\" + name);
                        try {
                            DownloadStartBtn1.setText("İNDİRMEYE BAŞLA (" + (--gerisay) + " Resim)");
                            AnaJframe.logtext1.append("Başarılı \n");
                            FileUtils.copyURLToFile(aURL, kaydet);
                            linktablosu1.setValueAt("Bitti", i, 1);
                        } catch (IOException ex) {
                            Logger.getLogger(AnaJframe.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } catch (MalformedURLException ex) {
                        Logger.getLogger(AnaJframe.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
        });
        c.start();

        goster1.setEnabled(true);
        AnaJframe.jButton4.setEnabled(true);
        AnaJframe.jButton5.setEnabled(false);

    }//GEN-LAST:event_DownloadStartBtn1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) linktablosu1.getModel();
        dtm.setRowCount(0);

        ts = new Thread(new Runnable() {
            @Override
            public void run() {

                try {
                    Properties prop = new Properties();
                    InputStream input = null;

                    input = new FileInputStream("config.properties");
                    prop.load(input);
                    String consumerKey = prop.getProperty("consumerKey");
                    String consumerSecret = prop.getProperty("consumerSecret");
                    String accessToken = prop.getProperty("accessToken");
                    String accessSecret = prop.getProperty("accessSecret");

                    ConfigurationBuilder cb = new ConfigurationBuilder();

                    cb.setOAuthConsumerKey(consumerKey);
                    cb.setOAuthConsumerSecret(consumerSecret);
                    cb.setOAuthAccessToken(accessToken);
                    cb.setOAuthAccessTokenSecret(accessSecret);

                    java.util.List statuses = null;

                    Twitter twitter = new TwitterFactory(cb.build()).getInstance();

                    String userName = jTextField2.getText();

                    for (int i = 1; i <= Integer.parseInt(startfield1.getText()); i++) {
                        Thread.sleep(1000);
                        Paging page = new Paging(i, 20);//page number, number per page
                        try {
                            for (Status status : twitter.getUserTimeline(userName, page)) {
                                for (MediaEntity mediaEntity : status.getMediaEntities()) {
                                    if (!mediaEntity.getMediaURL().contains("video_thumb")) {
                                        DefaultTableModel model = (DefaultTableModel) AnaJframe.linktablosu1.getModel();
                                        model.addRow(new Object[]{mediaEntity.getMediaURL(), "Bekliyor"});
                                        AnaJframe.DownloadStartBtn1.setText("İNDİRMEYE BAŞLA (" + AnaJframe.linktablosu1.getRowCount() + " Resim)");
                                    }
                                }
                            }
                        } catch (TwitterException ex) {
                            Logger.getLogger(AnaJframe.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }

                    AnaJframe.DownloadStartBtn1.setEnabled(true);
                    AnaJframe.jButton4.setEnabled(false);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(AnaJframe.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(AnaJframe.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InterruptedException ex) {
                    Logger.getLogger(AnaJframe.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
        ts.start();
        AnaJframe.jButton5.setEnabled(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        AnaJframe.DownloadStartBtn1.setEnabled(true);
        this.ts.stop();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        Properties prop = new Properties();
        OutputStream output = null;

        try {
            output = new FileOutputStream("config.properties");
            File f = new File("config.properties");
            if (f.exists()) {
                f.delete();
            } else {

            }
            // set the properties value
            prop.setProperty("CoderBy", "Sabri Yasin");
            prop.setProperty("consumerKey", jTextField3.getText());
            prop.setProperty("consumerSecret", jTextField4.getText());
            prop.setProperty("accessToken", jTextField5.getText());
            prop.setProperty("accessSecret", jTextField6.getText());
            // save properties to project root folder
            prop.store(output, null);

        } catch (IOException io) {
        } finally {
            if (output != null) {
                try {
                    output.close();
                } catch (IOException e) {
                }
            }

        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        File f = new File("config.properties");
        if (f.exists()) {

        } else {
            JOptionPane.showMessageDialog(null, "Twitter İçin Ayarlar Sekmesini Düzenleyiniz", "Bilgi", 1);
        }

        Properties prop = new Properties();
        InputStream input = null;

        try {
            input = new FileInputStream("config.properties");
            prop.load(input);

            prop.getProperty("CoderBy");

            jTextField3.setText(prop.getProperty("consumerKey"));
            jTextField4.setText(prop.getProperty("consumerSecret"));
            jTextField5.setText(prop.getProperty("accessToken"));
            jTextField6.setText(prop.getProperty("accessSecret"));

        } catch (IOException ex) {
        } finally {
            if (input != null) {
                try {
                    input.close();
                } catch (IOException e) {
                }
            }
        }


    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AnaJframe().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton DownloadStartBtn;
    public static javax.swing.JButton DownloadStartBtn1;
    private javax.swing.JButton goster;
    private javax.swing.JButton goster1;
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public static javax.swing.JButton jButton4;
    public static javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    public static javax.swing.JTable linktablosu;
    public static javax.swing.JTable linktablosu1;
    public static javax.swing.JTextArea logtext;
    public static javax.swing.JTextArea logtext1;
    public static javax.swing.JTextField startfield;
    public static javax.swing.JTextField startfield1;
    public static javax.swing.JTextField stopfield;
    // End of variables declaration//GEN-END:variables
}
